const residences = [
    {
        value: 'TP Hồ Chí Minh',
        label: 'TP Hồ Chí Minh',
        children: [
            {
                value: 'Quận 1',
                label: 'Quận 1',
                children: [
                    { label: 'Phường Bến Nghé', value: 'Phường Bến Nghé', },
                    { label: 'Phường Bến Thành', value: 'Phường Bến Thành', },
                    { label: 'Phường Cô Giang', value: 'Phường Cô Giang', },
                    { label: 'Phường Cầu Kho', value: 'Phường Cầu Kho', },
                    { label: 'Phường Cầu Ông Lãnh', value: 'Phường Cầu Ông Lãnh', },
                    { label: 'Phường Nguyễn Cư Trinh', value: 'Phường Nguyễn Cư Trinh', },
                    { label: 'Phường Nguyễn Thái Bình', value: 'Phường Nguyễn Thái Bình', },
                    { label: 'Phường Phạm Ngũ Lão', value: 'Phường Phạm Ngũ Lão', },
                    { label: 'Phường Tân Định', value: 'Phường Tân Định', },
                    { label: 'Phường Đa Kao', value: 'Phường Đa Kao', },
                ],
            },
            {
                value: 'Quận 3',
                label: 'Quận 3',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 04', value: 'Phường 04', },
                    { label: 'Phường 05', value: 'Phường 05', },
                    { label: 'Phường 09', value: 'Phường 09', },
                    { label: 'Phường 10', value: 'Phường 10', },
                    { label: 'Phường 11', value: 'Phường 11', },
                    { label: 'Phường 12', value: 'Phường 12', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },
                    { label: 'Phường Võ Thị Sáu', value: 'Phường Võ Thị Sáu', },
                ],
            },
            {
                value: 'Quận 4',
                label: 'Quận 4',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 04', value: 'Phường 04', },
                    { label: 'Phường 06', value: 'Phường 06', },
                    { label: 'Phường 08', value: 'Phường 08', },
                    { label: 'Phường 09', value: 'Phường 09', },
                    { label: 'Phường 10', value: 'Phường 10', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },
                    { label: 'Phường 15', value: 'Phường 15', },
                    { label: 'Phường 16', value: 'Phường 16', },
                    { label: 'Phường 18', value: 'Phường 18', },
                ],
            },
            {
                value: 'Quận 5',
                label: 'Quận 5',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 04', value: 'Phường 04', },
                    { label: 'Phường 05', value: 'Phường 05', },
                    { label: 'Phường 06', value: 'Phường 06', },
                    { label: 'Phường 07', value: 'Phường 07', },
                    { label: 'Phường 08', value: 'Phường 08', },
                    { label: 'Phường 09', value: 'Phường 09', },
                    { label: 'Phường 10', value: 'Phường 10', },
                    { label: 'Phường 11', value: 'Phường 11', },
                    { label: 'Phường 12', value: 'Phường 12', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },
                ],
            },
            {
                value: 'Quận 6',
                label: 'Quận 6',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 04', value: 'Phường 04', },
                    { label: 'Phường 05', value: 'Phường 05', },
                    { label: 'Phường 06', value: 'Phường 06', },
                    { label: 'Phường 07', value: 'Phường 07', },
                    { label: 'Phường 08', value: 'Phường 08', },
                    { label: 'Phường 09', value: 'Phường 09', },
                    { label: 'Phường 10', value: 'Phường 10', },
                    { label: 'Phường 11', value: 'Phường 11', },
                    { label: 'Phường 12', value: 'Phường 12', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },

                ],
            },
            {
                value: 'Quận 7',
                label: 'Quận 7',
                children: [
                    { label: 'Phường Bình Thuận', value: 'Phường Bình Thuận', },
                    { label: 'Phường Phú Mỹ', value: 'Phường Phú Mỹ', },
                    { label: 'Phường Phú Thuận', value: 'Phường Phú Thuận', },
                    { label: 'Phường Tân Hưng', value: 'Phường Tân Hưng', },
                    { label: 'Phường Tân Kiểng', value: 'Phường Tân Kiểng', },
                    { label: 'Phường Tân Phong', value: 'Phường Tân Phong', },
                    { label: 'Phường Tân Phú', value: 'Phường Tân Phú', },
                    { label: 'Phường Tân Quy', value: 'Phường Tân Quy', },
                    { label: 'Phường Tân Thuận Tây', value: 'Phường Tân Thuận Tây', },
                    { label: 'Phường Tân Thuận Đông', value: 'Phường Tân Thuận Đông', },

                ],
            },
            {
                value: 'Quận 8',
                label: 'Quận 8',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 04', value: 'Phường 04', },
                    { label: 'Phường 05', value: 'Phường 05', },
                    { label: 'Phường 06', value: 'Phường 06', },
                    { label: 'Phường 07', value: 'Phường 07', },
                    { label: 'Phường 08', value: 'Phường 08', },
                    { label: 'Phường 09', value: 'Phường 09', },
                    { label: 'Phường 10', value: 'Phường 10', },
                    { label: 'Phường 11', value: 'Phường 11', },
                    { label: 'Phường 12', value: 'Phường 12', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },
                    { label: 'Phường 15', value: 'Phường 15', },
                    { label: 'Phường 16', value: 'Phường 16', },

                ],
            },
            {
                value: 'Quận Bình Tân',
                label: 'Quận Bình Tân',
                children: [
                    { label: 'Phường An Lạc', value: 'Phường An Lạc', },
                    { label: 'Phường An Lạc A', value: 'Phường An Lạc A', },
                    { label: 'Phường Bình Hưng Hoà A', value: 'Phường Bình Hưng Hoà A', },
                    { label: 'Phường Bình Hưng Hoà B', value: 'Phường Bình Hưng Hoà B', },
                    { label: 'Phường Bình Hưng Hòa', value: 'Phường Bình Hưng Hòa', },
                    { label: 'Phường Bình Trị Đông', value: 'Phường Bình Trị Đông', },
                    { label: 'Phường Bình Trị Đông A', value: 'Phường Bình Trị Đông A', },
                    { label: 'Phường Bình Trị Đông B', value: 'Phường Bình Trị Đông B', },
                    { label: 'Phường Tân Tạo', value: 'Phường Tân Tạo', },
                    { label: 'Phường Tân Tạo A', value: 'Phường Tân Tạo A', },

                ],
            },
            {
                value: 'Quận Bình Thạnh',
                label: 'Quận Bình Thạnh',
                children: [
                    { label: 'Phường 01', value: 'Phường 01', },
                    { label: 'Phường 02', value: 'Phường 02', },
                    { label: 'Phường 03', value: 'Phường 03', },
                    { label: 'Phường 05', value: 'Phường 05', },
                    { label: 'Phường 06', value: 'Phường 06', },
                    { label: 'Phường 07', value: 'Phường 07', },
                    { label: 'Phường 11', value: 'Phường 11', },
                    { label: 'Phường 12', value: 'Phường 12', },
                    { label: 'Phường 13', value: 'Phường 13', },
                    { label: 'Phường 14', value: 'Phường 14', },
                    { label: 'Phường 15', value: 'Phường 15', },
                    { label: 'Phường 17', value: 'Phường 17', },
                    { label: 'Phường 19', value: 'Phường 19', },
                    { label: 'Phường 21', value: 'Phường 21', },
                    { label: 'Phường 22', value: 'Phường 22', },
                    { label: 'Phường 24', value: 'Phường 24', },
                    { label: 'Phường 25', value: 'Phường 25', },
                    { label: 'Phường 26', value: 'Phường 26', },
                    { label: 'Phường 27', value: 'Phường 27', },
                    { label: 'Phường 28', value: 'Phường 28', },

                ],
            },
            {
                value: 'Quận 6',
                label: 'Quận 6',
                children: [
                    {
                        value: 'Phường',
                        label: 'Phường',
                    },
                ],
            },
            {
                value: 'Quận 6',
                label: 'Quận 6',
                children: [
                    {
                        value: 'Phường',
                        label: 'Phường',
                    },
                ],
            },
        ],
    },
];

export default residences